receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:5555

processors:
  batch:
    timeout: 1s
    send_batch_size: 1024

exporters:
  logging:
    loglevel: debug
  otlp:
    endpoint: tempo:4317
    tls:
      insecure: true
  prometheus:
    endpoint: collector:18888
    namespace: default

service:
  pipelines:
    metrics:
      receivers: [otlp]
#      processors: [batch]
      exporters: [logging, prometheus]
    traces:
      receivers: [otlp]
#      processors: [batch]
      exporters: [logging, otlp]
